.PHONY: all clean

all: README.md

README.md: guessinggame.sh
	@echo "# The Unix Workbench Course Peer-Graded Assignment" > README.md
	@echo "by Johns Hopkins University on coursera.org." >> README.md
	@echo "**Author:** Ilyass Salim" >> README.md
	@echo "" >> README.md
	@echo "## Description" >> README.md
	@echo "make a program called guessinggame.sh. This program should continuously ask the user to guess the number of files in the current directory, until they guess the correct number. The user is informed if their guess is too high or too low. Once the user guesses the correct number of files in the current directory they should be congratulated." >> README.md
	@echo "" >> README.md
	@echo "## Make date: $$(date)" >> README.md
	@echo "## Number of lines in guessinggame.sh: $$(wc -l < guessinggame.sh)" >> README.md
	@echo "" >> README.md
	@echo "KUDOS!!!" >> README.md
	@echo "" >> README.md
	@echo "Warm Regards," >> README.md
	@echo "Ilyass Salim" >> README.md

clean:
	rm -f README.md
